config/routes.rb
Rails.application.routes.draw do
  
  root "hablas#index"
  
  resources :hablas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/habla.rb
class Habla < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/hablas_controller.rb
class HablasController < ApplicationController
  before_action :set_habla, only: [:show, :edit, :update, :destroy]

  # GET /hablas
  # GET /hablas.json
  def index
    @hablas = Habla.all
  end

  # GET /hablas/1
  # GET /hablas/1.json
  def show
  end

  # GET /hablas/new
  def new
    @habla = Habla.new
  end

  # GET /hablas/1/edit
  def edit
  end

  # POST /hablas
  # POST /hablas.json
  def create
    @habla = Habla.new(habla_params)

    respond_to do |format|
      if @habla.save
        format.html { redirect_to @habla, notice: 'Habla was successfully created.' }
        format.json { render :show, status: :created, location: @habla }
      else
        format.html { render :new }
        format.json { render json: @habla.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hablas/1
  # PATCH/PUT /hablas/1.json
  def update
    respond_to do |format|
      if @habla.update(habla_params)
        format.html { redirect_to @habla, notice: 'Habla was successfully updated.' }
        format.json { render :show, status: :ok, location: @habla }
      else
        format.html { render :edit }
        format.json { render json: @habla.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hablas/1
  # DELETE /hablas/1.json
  def destroy
    @habla.destroy
    respond_to do |format|
      format.html { redirect_to hablas_url, notice: 'Habla was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_habla
      @habla = Habla.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def habla_params
      params.require(:habla).permit(:dictate)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hablas_helper.rb
module HablasHelper
end

app/views/hablas/_form.html.erb
<%= form_for(habla) do |f| %>
  <% if habla.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(habla.errors.count, "error") %> prohibited this habla from being saved:</h2>

      <ul>
      <% habla.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dictate %>
    <%= f.text_area :dictate, :id => "final_transcript" %> 

    <div>
  <a href="#" id="start_button" onclick="startDictation(event)">Dictate</a>
</div>

<div id="results">
  <span id="final_span" class="final"></span>
  <span id="interim_span" class="interim"></span>
</div>

<script type="text/javascript">
var final_transcript = '';
var recognizing = false;

var r =  document.getElementById('final_transcript');
  
if ('webkitSpeechRecognition' in window) {

  var recognition = new webkitSpeechRecognition();

  recognition.continuous = true;
  recognition.interimResults = true;

  recognition.onstart = function() {
    recognizing = true;
  };

  recognition.onerror = function(event) {
    console.log(event.error);
  };

  recognition.onend = function() {
    recognizing = false;
  };

  recognition.onresult = function(event) {
    var interim_transcript = '';
    for (var i = event.resultIndex; i < event.results.length; ++i) {
      if (event.results[i].isFinal) {
        final_transcript += event.results[i][0].transcript;
      } else {
        interim_transcript += event.results[i][0].transcript;
      }
    }
    final_transcript = capitalize(final_transcript);
    final_span.innerHTML = linebreak(final_transcript);
    interim_span.innerHTML = linebreak(interim_transcript);
    r.innerHTML = linebreak(final_transcript);
  };
}

var two_line = /\n\n/g;
var one_line = /\n/g;
function linebreak(s) {
  return s.replace(two_line, '<p></p>').replace(one_line, '<br>');
}

function capitalize(s) {
  return s.replace(s.substr(0,1), function(m) { return m.toUpperCase(); });
}

function startDictation(event) {
  if (recognizing) {
    recognition.stop();
    return;
  }
  final_transcript = '';
  recognition.lang = 'en-US';
  recognition.start();
  final_span.innerHTML = '';
  interim_span.innerHTML = '';
}
</script>




  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hablas/edit.html.erb
<h1>Editing Habla</h1>

<%= render 'form', habla: @habla %>

<%= link_to 'Show', @habla %> |
<%= link_to 'Back', hablas_path %>

app/views/hablas/index.html.erb
<p id="notice"><%= notice %></p>

<!DOCTYPE html>

<html>

<h1>Hablas</h1>

<table>
  <thead>
    <tr>
      <th>Dictate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hablas.each do |habla| %>
      <tr>
        <td><%= habla.dictate %></td>
        <td><%= link_to 'Show', habla %></td>
        <td><%= link_to 'Edit', edit_habla_path(habla) %></td>
        <td><%= link_to 'Destroy', habla, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Habla', new_habla_path %>






    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.1/css/font-awesome.min.css" />
    <style type="text/css">
      body{
        font-family: verdana;
      }
      #result{
        height: 200px;
        border: 1px solid #ccc;
        padding: 10px;
        box-shadow: 0 0 10px 0 #bbb;
        margin-bottom: 30px;
        font-size: 14px;
        line-height: 25px;
      }
      button{
        font-size: 20px;
        position: absolute;
        top: 240px;
        left: 50%;
      }
    </style>
  </head>
  <body>
    <h4 align="center">Speech to text converter in JS</h4>
    <div id="result"></div>
    <button onclick="startConverting();"><i class="fa fa-microphone"></i></button>
    <script type="text/javascript">

      var r = document.getElementById('result');

      function startConverting () {
        if('webkitSpeechRecognition' in window){
          var speechRecognizer = new webkitSpeechRecognition();
          speechRecognizer.continuous = true;
          speechRecognizer.interimResults = true;
          speechRecognizer.lang = 'en-IN';
          speechRecognizer.start();

          var finalTranscripts = '';

          speechRecognizer.onresult = function(event){
            var interimTranscripts = '';
            for(var i = event.resultIndex; i < event.results.length; i++){
              var transcript = event.results[i][0].transcript;
              transcript.replace("\n", "<br>");
              if(event.results[i].isFinal){
                finalTranscripts += transcript;
              }else{
                interimTranscripts += transcript;
              }
            }
            r.innerHTML = finalTranscripts + '<span style="color:#999">' + interimTranscripts + '</span>';
          };
          speechRecognizer.onerror = function (event) {
          };
        }else{
          r.innerHTML = 'Your browser is not supported. If google chrome, please upgrade!';
        }
      }

      

    </script>
  </body>

app/views/hablas/new.html.erb
<h1>New Habla</h1>

<%= render 'form', habla: @habla %>

<%= link_to 'Back', hablas_path %>

app/views/hablas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @habla.dictate %>
</p>

<%= link_to 'Edit', edit_habla_path(@habla) %> |
<%= link_to 'Back', hablas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Speechtest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>